tablecatchup: main.go
	go build -gcflags=all="-N -l"
clean:
	rm tablecatchup
install:
	cp tablecatchup /home/snowao/code/kunlun/service/node_mgr/build/output/bin/util
	cp tablecatchup /home/snowao/code/kunlun/service/node_mgr/resource/util
