title = "cnf template"

[restore]
ColdBackupFilePath = ""
BinlogBackupFilePath = "/"
DefaultFile = ""
GlobalConsistentEnable = false
RestoreTime = ""

[backup]
MysqlEtcFilePath=""
StorageType = "hdfs"
ClusterName = "clust1"

